apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s
spec:
  replicas: 1 # The HPA will instantly change this to 2 once applied
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: kubernete
        image: simanta96/devops-integration:latest
        ports:
        - containerPort: 8090
        # 👇 ADD THESE LINES TO YOUR DEPLOYMENT.YAML 👇
        resources:
          requests:
            cpu: "200m"   # Reservation: The HPA uses this value to calculate the 70% load
          limits:
            cpu: "500m"   # Throttling limit